export const stockData = [
  // {
  //     id: 1,
  //     S_N: '1',
  //     company_name: 'NIBL STABLE FUND - NSFUND (IPO - Mutual Fund)',
  //     issue_manager: 'NIMB ACE CAPITAL LIMITED',
  //     issued_unit: '100000000',
  //     number_of_applications: '43571',
  //     applied_unit: '103092860',
  //     amount: '1030928600',
  //     open_date: '2024-01-16',
  //     close_date: '2024-01-30',
  //     last_update: '2024-01-30 17:06:10',
  //     issue_type: 'IPO'
  //   }
  {
    id: 1,
    issue_type: "currentIssue",
    company_name: "Sarbottam Cement Limited",
    units: "9,30,000",
    target: "Local",
    openDate: "Jan 10",
    closeDate: "Jan 14",
    status: "Open",
  },
  {
    id: 2,
    type: "currentIssue",
    company: "Siddhartha Equity Fund",
    units: "1,00,00,000",
    target: "Local",
    openDate: "Jan 10",
    closeDate: "Jan 14",
    status: "Open",
  },
  {
    id: 3,
    type: "currentIssue",
    company: "Siddhartha Equity Fund",
    units: "1,00,00,000",
    target: "Local",
    openDate: "Jan 10",
    closeDate: "Jan 14",
    status: "Open",
  },
  {
    id: 4,
    type: "currentIssue",
    company: "Siddhartha Equity Fund",
    units: "1,00,00,000",
    target: "Local",
    openDate: "Jan 10",
    closeDate: "Jan 14",
    status: "Open",
  },
  {
    id: 5,
    type: "currentIssue",
    company: "Siddhartha Equity Fund",
    units: "1,00,00,000",
    target: "Local",
    openDate: "Jan 10",
    closeDate: "Jan 14",
    status: "Open",
  },
  {
    id: 6,
    type: "currentIssue",
    company: "Siddhartha Equity Fund",
    units: "1,00,00,000",
    target: "Local",
    openDate: "Jan 10",
    closeDate: "Jan 14",
    status: "Open",
  },
  {
    id: 7,
    type: "currentIssue",
    company: "Siddhartha Equity Fund",
    units: "1,00,00,000",
    target: "Local",
    openDate: "Jan 10",
    closeDate: "Jan 14",
    status: "Open",
  },
  {
    id: 8,
    type: "currentIssue",
    company: "Siddhartha Equity Fund",
    units: "1,00,00,000",
    target: "Local",
    openDate: "Jan 10",
    closeDate: "Jan 14",
    status: "Open",
  },
  {
    id: 9,
    type: "currentIssue",
    company: "Siddhartha Equity Fund",
    units: "1,00,00,000",
    target: "Local",
    openDate: "Jan 10",
    closeDate: "Jan 14",
    status: "Open",
  },
  {
    id: 9,
    type: "currentIssue",
    company: "Siddhartha Equity Fund",
    units: "1,00,00,000",
    target: "Local",
    openDate: "Jan 10",
    closeDate: "Jan 14",
    status: "Open",
  },
  {
    id: 9,
    type: "currentIssue",
    company: "Siddhartha Equity Fund",
    units: "1,00,00,000",
    target: "Local",
    openDate: "Jan 10",
    closeDate: "Jan 14",
    status: "Open",
  },
  {
    id: 9,
    type: "currentIssue",
    company: "Siddhartha Equity Fund",
    units: "1,00,00,000",
    target: "Local",
    openDate: "Jan 10",
    closeDate: "Jan 14",
    status: "Open",
  },
  {
    id: 9,
    type: "currentIssue",
    company: "Siddhartha Equity Fund",
    units: "1,00,00,000",
    target: "Local",
    openDate: "Jan 10",
    closeDate: "Jan 14",
    status: "Open",
  },
  {
    id: 9,
    type: "currentIssue",
    company: "Siddhartha Equity Fund",
    units: "1,00,00,000",
    target: "Local",
    openDate: "Jan 10",
    closeDate: "Jan 14",
    status: "Open",
  },
  {
    id: 9,
    type: "currentIssue",
    company: "Siddhartha Equity Fund",
    units: "1,00,00,000",
    target: "Local",
    openDate: "Jan 10",
    closeDate: "Jan 14",
    status: "Open",
  },
  {
    id: 9,
    type: "currentIssue",
    company: "Siddhartha Equity Fund",
    units: "1,00,00,000",
    target: "Local",
    openDate: "Jan 10",
    closeDate: "Jan 14",
    status: "Open",
  },
  {
    id: 9,
    type: "currentIssue",
    company: "Siddhartha Equity Fund",
    units: "1,00,00,000",
    target: "Local",
    openDate: "Jan 10",
    closeDate: "Jan 14",
    status: "Open",
  },
  {
    id: 9,
    type: "currentIssue",
    company: "Siddhartha Equity Fund",
    units: "1,00,00,000",
    target: "Local",
    openDate: "Jan 10",
    closeDate: "Jan 14",
    status: "Open",
  },
  {
    id: 9,
    type: "currentIssue",
    company: "Siddhartha Equity Fund",
    units: "1,00,00,000",
    target: "Local",
    openDate: "Jan 10",
    closeDate: "Jan 14",
    status: "Open",
  },
];
